# Generated by Django 5.0.6 on 2024-06-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_alter_message_message_alter_message_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatApp.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
