# Generated by Django 5.0.6 on 2024-07-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
